image: python:latest

default:
  tags:
    - shelllocal

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

Tests with allure:
  stage: test
  script:
    - pytest
    - allure generate -c -o tests/allure-results

  artifacts:
    paths:
      - tests/allure-results
