image: python:latest

default:
  tags:
    - shelllocal

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

Tests with allure:
  stage: test
  script:
    - pytest
    - allure generate -c allure-results -o allure-report

  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/allure-results
      - $CI_PROJECT_DIR/allure-report